name: Test and Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run Unit Tests
        run: go test -v -race ./...

      - name: Build the Binary
        run: go build -o chatserver ./cmd/server/
